baseurl = "https://maxdeliso.name/"
title = "Reflections"
copyright = "Copyright &copy; 2018, 2019 - Joseph Maximilian DeLiso"
languageCode = "en-us"
theme = "kiera"
pygmentsCodeFences = true
disqusShortname = "maxdeliso-name"

[params]
    tagline = "a sparse bag of words, oft neglected"

[author]
    name = "Max DeLiso"
    github = "maxdeliso"
    linkedin = "jmdeliso"
    twitter = "jmdeliso"
    instagram = "jmdeliso"